name: action name
author: action author
description: action description
inputs:
  token:
    description: GitHub auth token to authorize uploading release assets
    required: false
    default: ${{ github.token }}
  staging-path:
    description: Path where generated assets will be saved (set as output as well).
    required: false
    default: ${{ runner.temp }}/assets
outputs:
  staging-path:
    description: Path where generated assets were saved.
    value: ${{ inputs.staging-path }}
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/action.ps1
      shell: pwsh
      id: script
    - run: |
        Write-Host $env:GITHUB_CTX
        Write-Host $env:STEPS_CTX
      shell: pwsh
      env:
        GITHUB_CTX: ${{ toJson(github) }}
        STEPS_CTX: ${{ toJson(steps) }}
branding:
  icon: book-open
  color: blue
