name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - shell: pwsh
      run: Write-Host $env:GITHUB_TOKEN
    
    - uses: ./.github/actions/composite

    - name: Read .NET Core SDK version
      id: globaljson
      uses: Amadevus/pwsh-script@master
      with:
        script: |
          $version = (Get-Content global.json -Raw | ConvertFrom-Json).sdk.version
          Set-ActionOutput version $version
          Write-Host "color blue" -ForegroundColor Blue
          return ('some test result: ' + $github.event.sender.login)
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ steps.globaljson.outputs.version }}
      
    - run: dotnet --info
    - run: dotnet restore -v m
    - run: dotnet build --no-restore -c Release
    - run: dotnet pack -c Release
    - shell: pwsh
      run: |
        $ghp = "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json".ToLower()
        dotnet nuget add source $ghp -n github -u ${{ github.actor }} -p ${{ github.token }} --store-password-in-clear-text
        Get-ChildItem ~/* -Recurse -Force -ErrorAction:Continue | ? Name -IMatch '^nuget\.config$' | select -ExpandProperty FullName
        Get-Content ~/.nuget/NuGet/NuGet.Config
        # dotnet nuget push src/bin/Release/*.nupkg -s github
