name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - shell: pwsh
      run: |
        $ws = $env:GITHUB_WORKSPACE
        echo $ws
        pushd $ws
        echo "In: $(pwd)"
        ls
        cd ..
        echo "In: $(pwd)"
        ls
        cd ..
        echo "In: $(pwd)"
        ls
    - name: test pwsh
      shell: pwsh
      run: |
        Write-Output "output"
        Write-Host "host"
        Write-Information "info"
        Write-Warning "warning"
        Write-Verbose "verbose"
    - name: Print event
      env:
        JSON: ${{ toJson(github.event) }}
      run: echo "$JSON"
