name: CI

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Read .NET Core SDK version
      id: globaljson
      shell: pwsh
      run: Write-Host "::set-output name=version::$((Get-Content global.json -Raw | ConvertFrom-Json).sdk.version)"

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ steps.globaljson.outputs.version }}
      
    - run: dotnet --info
    - run: dotnet restore -v m
    - run: dotnet build --no-restore -c Release