name: issue test

on:
  issues:
    types: [opened]

jobs:
  open-new:
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh
        run: |
          $repo = "WarHub-Warden-testrepo/bsdata-json-test"
          $url = "https://api.github.com/repos/$repo/issues"
          $body = @{
            title = "Test issue"
            body = "$env:GITHUB_ACTOR opened a new issue in test-actions."
          } | ConvertTo-Json -Compress
          $headers = @{ Authorization = "token ${{ secrets.GITHUB_TOKEN }}" }
          Invoke-RestMethod $url -Method Post -Headers $headers -Body $body -ContentType "application/json"
