name: issue test

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  open-new:
    runs-on: ubuntu-latest
    steps:
      - run: echo $event
        env:
          event: ${{ toJSON(github.event) }}
