name: Release

on:
  release:
    types: [published, created, edited, released]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Print event
      env:
        JSON: ${{ toJson(github.event) }}
      run: echo "$JSON"
