name: Release

on:
  release:
    types: [created, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Print event
      env:
        JSON: ${{ toJson(github.event) }}
      run: echo "$JSON"
    - name: print github context
      env:
        JSON: ${{ toJson(github) }}
      run: echo "$JSON"
